disabled = false
languageCode = "zh-cn"
languageName = "Chinese"
weight = 0
title = "RonのBLOG"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "专属于某脚本小子的桥洞"
  copyright = "&copy; Ron1337 2024-NOW <a href=\"https://beian.miit.gov.cn/\">粤ICP备2024303235号</a>"

[params.author]
  name = "Ron#1337"
  email = "zzpengroot@outlook.com"
  image = "img/authors/ron.jpg"
#   imageQuality = 96
  headline = "某不知名脚本小子"
  bio = "某不知名脚本小子"
  links = [
    { email = "mailto:zzpengroot@outlook.com" },
#     { link = "https://ron1337.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/R0n1337" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = "https://t.me/ZZPeng" }
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]